export const MEMBER = {
  MEMBER: "/member/",
  FAST_ADD_FIELDS: "/member/fast-add-fields/",
  TASK: "/member/task/",
  ALERT: "/member/alert/",
  MEMBER_SERVICES: "/member/services/",
  MEMBER_RECURRING_SERVICES: "/member/recurring-services/",
  MEMBER_SERVICE_REDEEM: "/member/redeem/",
  MEMBER_RESOURCE_USAGE: "/member/redeem/resource-usage/",
  MEMBER_REWARDS: "/member/rewards/",
  MEMBER_REWARDS_ADJUST: "/member/rewards/",
  MEMBER_AGREEMENT: "/member/agreement/",
  MEMBER_AGREEMENT_VIEW: "/member/agreement/view/",
  MEMBER_REDEEMABLE: "/member/redeemable/",
  MEMBER_RELATIONSHIPS: "/member/relationships/",
  CHARGE_SCHEDULES: "/member/agreement/charge-schedules",
  BILLING_HISTORY: "/member/billing-history/",
  POS_HISTORY: "/member/pos-history/",
  DOCUMENT: "/member/document/",
  VERIFY_BARCODE: "/member/verify-barcode",
  VERIFY_EMAIL: "/member/verify-email",
  IPOS_CARD_TOKENS: "/member/",
  PENDING_EVENT_SERVICES_PREFIX: "/member/",
  PENDING_EVENT_SERVICES_SUFFIX: "/pending-event-services",
  MEMBER_PAST_DUE: "/member/past-due/",
};
