// member data points
export const purchasedServiceDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Profit Center', _id: 'PROFIT_CENTER', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Item Name', _id: 'ITEM_NAME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Item Sku', _id: 'ITEM_SKU', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Item UPC', _id: 'ITEM_UPC', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Item Price', _id: 'ITEM_PRICE', isNumber: true, type: 'PURCHASED_SERVICES' },
    { title: 'Item Discount', _id: 'ITEM_DISCOUNT', isNumber: true, type: 'PURCHASED_SERVICES' },
    { title: 'Item Tax', _id: 'ITEM_TAX', isNumber: true, type: 'PURCHASED_SERVICES' },
    { title: 'Item Total', _id: 'ITEM_TOTAL', isNumber: true, type: 'PURCHASED_SERVICES' },
    { title: 'Item Quantity', _id: 'ITEM_QUANTITY', isNumber: true, type: 'PURCHASED_SERVICES' },
    { title: 'Expiration Date', _id: 'EXPIRATION_DATE', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sales Person', _id: 'SALES_PERSON', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sales Person (Last Name)', _id: 'SALES_PERSON_LAST_NAME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sales Person (Last Name, First Name)', _id: 'SALES_PERSON_FULL_NAME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sales Code', _id: 'SALES_CODE', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Discount Code', _id: 'DISCOUNT_CODE', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sale Date', _id: 'SALE_DATE', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sale Date/Time', _id: 'SALE_DATE_TIME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Sale Time', _id: 'SALE_TIME', isNumber: false, type: 'PURCHASED_SERVICES' },
    { title: 'Payment Method', _id: 'PAYMENT_METHOD', isNumber: false, type: 'PURCHASED_SERVICES' },
];

export const purchasedProductDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Profit Center', _id: 'PROFIT_CENTER', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Name', _id: 'ITEM_NAME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Sku', _id: 'ITEM_SKU', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Item UPC', _id: 'ITEM_UPC', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Price', _id: 'ITEM_PRICE', isNumber: true, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Discount', _id: 'ITEM_DISCOUNT', isNumber: true, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Tax', _id: 'ITEM_TAX', isNumber: true, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Total', _id: 'ITEM_TOTAL', isNumber: true, type: 'PURCHASED_PRODUCT' },
    { title: 'Item Quantity', _id: 'ITEM_QUANTITY', isNumber: true, type: 'PURCHASED_PRODUCT' },
    { title: 'Sales Person (First Name)', _id: 'SALES_PERSON_FIRST_NAME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sales Person (Last Name)', _id: 'SALES_PERSON_LAST_NAME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sales Person (Last Name, First Name)', _id: 'SALES_PERSON_FULL_NAME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sales Code', _id: 'SALES_CODE', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Discount Code', _id: 'DISCOUNT_CODE', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sale Date', _id: 'SALE_DATE', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sale Date/Time', _id: 'SALE_DATE_TIME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Sale Time', _id: 'SALE_TIME', isNumber: false, type: 'PURCHASED_PRODUCT' },
    { title: 'Payment Method', _id: 'PAYMENT_METHOD', isNumber: false, type: 'PURCHASED_PRODUCT' },
];

export const agreementDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'AGREEMENT' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'AGREEMENT' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'AGREEMENT' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'AGREEMENT' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'AGREEMENT' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'AGREEMENT' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'AGREEMENT' },
    { title: 'Agreement Category', _id: 'AGREEMENT_CATEGORY', isNumber: false, type: 'AGREEMENT' },
    { title: 'Agreement Sub Category', _id: 'AGREEMENT_SUB_CATEGORY', isNumber: false, type: 'AGREEMENT' },
    { title: 'Agreement Name', _id: 'AGREEMENT_NAME', isNumber: false, type: 'AGREEMENT' },
    { title: 'Agreement Status', _id: 'AGREEMENT_STATUS', isNumber: false, type: 'AGREEMENT' },
    { title: 'Billing Status', _id: 'BILLING_STATUS', isNumber: false, type: 'AGREEMENT' },
    { title: 'Start Date', _id: 'START_DATE', isNumber: false, type: 'AGREEMENT' },
    { title: 'Next Billing Date', _id: 'NEXT_BILLING_DATE', isNumber: false, type: 'AGREEMENT' },
    { title: 'Amount Due', _id: 'AMOUNT_DUE', isNumber: true, type: 'AGREEMENT' },
    { title: 'Days Past Due', _id: 'DAYS_PAST_DUE', isNumber: true, type: 'AGREEMENT' },
    { title: 'Last Check-in Date', _id: 'LAST_CHECKIN_DATE', isNumber: false, type: 'AGREEMENT' },
    { title: 'Campaign', _id: 'CAMPAIGN', isNumber: false, type: 'AGREEMENT' },
    { title: 'Member Referred By (Last Name, First Name)', _id: 'MEMBER_REFERRED_BY', isNumber: false, type: 'AGREEMENT' },
];

export const eventDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'EVENT' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'EVENT' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'EVENT' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'EVENT' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'EVENT' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'EVENT' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'EVENT' },
    { title: 'Event Type', _id: 'EVENT_TYPE', isNumber: false, type: 'EVENT' },
    { title: 'Event Name', _id: 'EVENT_NAME', isNumber: false, type: 'EVENT' },
    { title: 'Event Location', _id: 'EVENT_LOCATION', isNumber: false, type: 'EVENT' },
    { title: 'Staff Member (First Name)', _id: 'STAFF_MEMBER_FIRST_NAME', isNumber: false, type: 'EVENT' },
    { title: 'Staff Member (Last Name)', _id: 'STAFF_MEMBER_LAST_NAME', isNumber: false, type: 'EVENT' },
    { title: 'Staff Member (Last Name, First Name)', _id: 'STAFF_MEMBER_FULL_NAME', isNumber: false, type: 'EVENT' },
    { title: 'Event Status', _id: 'EVENT_STATUS', isNumber: false, type: 'EVENT' },
    { title: 'Date Booked (Date/ignore time)', _id: 'DATE_BOOKED_DATE_ONLY', isNumber: false, type: 'EVENT' },
    { title: 'Date Booked (Date and Time)', _id: 'DATE_BOOKED_DATE_TIME', isNumber: false, type: 'EVENT' },
    { title: 'Date Completed (Date/ignore time)', _id: 'DATE_COMPLETED_DATE_ONLY', isNumber: false, type: 'EVENT' },
    { title: 'Date Completed (Date and Time)', _id: 'DATE_COMPLETED_DATE_TIME', isNumber: false, type: 'EVENT' },
    { title: 'Date Attended (Date/ignore time)', _id: 'DATE_ATTENDED_DATE_ONLY', isNumber: false, type: 'EVENT' },
    { title: 'Date Attended (Date and Time)', _id: 'DATE_ATTENDED_DATE_TIME', isNumber: false, type: 'EVENT' },
    { title: 'Date Cancelled (Date/ignore time)', _id: 'DATE_CANCELLED_DATE_ONLY', isNumber: false, type: 'EVENT' },
    { title: 'Date Cancelled (Date and Time)', _id: 'DATE_CANCELLED_DATE_TIME', isNumber: false, type: 'EVENT' },
    { title: 'Service Used', _id: 'SERVICE_USED', isNumber: false, type: 'EVENT' },
    { title: 'Service Price', _id: 'SERVICE_PRICE', isNumber: true, type: 'EVENT' },
    { title: 'Session Quantity', _id: 'SESSION_QUANTITY', isNumber: true, type: 'EVENT' },
    { title: 'Member Verification', _id: 'MEMBER_VERIFICATION', isNumber: false, type: 'EVENT' },
    { title: 'Employee Verification', _id: 'EMPLOYEE_VERIFICATION', isNumber: false, type: 'EVENT' },
];

export const rewardsDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'REWARDS' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'REWARDS' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'REWARDS' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'REWARDS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'REWARDS' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'REWARDS' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'REWARDS' },
    { title: 'Rewards Point Balance', _id: 'REWARDS_POINT_BALANCE', isNumber: true, type: 'REWARDS' },
    { title: 'Reward Redeemed', _id: 'REWARD_REDEEMED', isNumber: true, type: 'REWARDS' },
    { title: 'Date of Redemption', _id: 'DATE_OF_REDEMPTION', isNumber: false, type: 'REWARDS' },
    { title: 'Redeemed Item', _id: 'REDEEMED_ITEM', isNumber: false, type: 'REWARDS' },
    { title: 'Reward Earned', _id: 'REWARD_EARNED', isNumber: true, type: 'REWARDS' },
    { title: 'Date Earned', _id: 'DATE_EARNED', isNumber: false, type: 'REWARDS' },
    { title: 'Earning Item', _id: 'EARNING_ITEM', isNumber: false, type: 'REWARDS' },
    { title: 'Manual Entry', _id: 'MANUAL_ENTRY', isNumber: false, type: 'REWARDS' },
    { title: 'Staff Member', _id: 'STAFF_MEMBER', isNumber: false, type: 'REWARDS' },
];

export const tasksDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'TASKS' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'TASKS' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'TASKS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'TASKS' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'TASKS' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'TASKS' },
    { title: 'Task Type', _id: 'TASK_TYPE', isNumber: false, type: 'TASKS' },
    { title: 'Task Message', _id: 'TASK_MESSAGE', isNumber: false, type: 'TASKS' },
    { title: 'Task Created Date (Ignore Time)', _id: 'TASK_CREATED_DATE', isNumber: false, type: 'TASKS' },
    { title: 'Task Created Date and Time', _id: 'TASK_CREATED_DATE_TIME', isNumber: false, type: 'TASKS' },
    { title: 'Task Completed Date (Ignore Time)', _id: 'TASK_COMPLETED_DATE', isNumber: false, type: 'TASKS' },
    { title: 'Task Completed Date and Time', _id: 'TASK_COMPLETED_DATE_TIME', isNumber: false, type: 'TASKS' },
    { title: 'Staff Assigned (First Name)', _id: 'STAFF_ASSIGNED_FIRST_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Staff Assigned (Last Name)', _id: 'STAFF_ASSIGNED_LAST_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Staff Assigned (Last Name, First Name)', _id: 'STAFF_ASSIGNED_FULL_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Task Created By (First Name)', _id: 'TASK_CREATED_BY_FIRST_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Task Created By (Last Name)', _id: 'TASK_CREATED_BY_LAST_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Task Created By (Last Name, First Name)', _id: 'TASK_CREATED_BY_FULL_NAME', isNumber: false, type: 'TASKS' },
    { title: 'Task Status', _id: 'TASK_STATUS', isNumber: false, type: 'TASKS' },
];

export const resourcesDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'RESOURCES' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'RESOURCES' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'RESOURCES' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'RESOURCES' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'RESOURCES' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'RESOURCES' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'RESOURCES' },
    { title: 'Resource Type', _id: 'RESOURCE_TYPE', isNumber: false, type: 'RESOURCES' },
    { title: 'Resource Name', _id: 'RESOURCE_NAME', isNumber: false, type: 'RESOURCES' },
    { title: 'Resource Quantity', _id: 'RESOURCE_QUANTITY', isNumber: true, type: 'RESOURCES' },
    { title: 'Resource Reserved Date (ignore Time)', _id: 'RESOURCE_RESERVED_DATE', isNumber: false, type: 'RESOURCES' },
    { title: 'Resource Reserved Date and Time', _id: 'RESOURCE_RESERVED_DATE_TIME', isNumber: false, type: 'RESOURCES' },
    { title: 'Past Due Status', _id: 'PAST_DUE_STATUS', isNumber: false, type: 'RESOURCES' },
];

export const serviceDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'SERVICE' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'SERVICE' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'SERVICE' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'SERVICE' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'SERVICE' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'SERVICE' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'SERVICE' },
    { title: 'Profit Center', _id: 'PROFIT_CENTER', isNumber: false, type: 'SERVICE' },
    { title: 'Service Name', _id: 'SERVICE_NAME', isNumber: false, type: 'SERVICE' },
    { title: 'Service Status', _id: 'SERVICE_STATUS', isNumber: false, type: 'SERVICE' },
    { title: 'Total Quantity', _id: 'TOTAL_QTY', isNumber: true, type: 'SERVICE' },
    { title: 'Used Quantity', _id: 'USED_QTY', isNumber: true, type: 'SERVICE' },
    { title: 'Remaining Quantity', _id: 'REMAINING_QTY', isNumber: true, type: 'SERVICE' },
    { title: 'Expiration Date', _id: 'EXPIRATION_DATE', isNumber: false, type: 'SERVICE' },
    { title: 'Expires In (Days)', _id: 'EXPIRES_IN_DAYS', isNumber: true, type: 'SERVICE' },
    { title: 'Purchase Date', _id: 'PURCHASE_DATE', isNumber: false, type: 'SERVICE' },
    { title: 'Last Used Date', _id: 'LAST_USED_DATE', isNumber: false, type: 'SERVICE' },
    { title: 'Service Price', _id: 'SERVICE_PRICE', isNumber: true, type: 'SERVICE' },
];

export const userIndexDataPoints = [
    { title: 'Member Name (Last,First)', _id: 'MEMBER_NAME', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'USER_INDEX' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'USER_INDEX' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Age', _id: 'MEMBER_AGE', isNumber: true, type: 'USER_INDEX' },
    { title: 'Member Gender', _id: 'MEMBER_GENDER', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Address (Street)', _id: 'MEMBER_ADDRESS_STREET', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Address (City)', _id: 'MEMBER_ADDRESS_CITY', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Address (State)', _id: 'MEMBER_ADDRESS_STATE', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Address (Zip)', _id: 'MEMBER_ADDRESS_ZIP', isNumber: false, type: 'USER_INDEX' },
    { title: 'Member Date of Birth (MM/DD/YYYY)', _id: 'MEMBER_DOB', isNumber: false, type: 'USER_INDEX' },
    { title: 'Campaign', _id: 'CAMPAIGN', isNumber: false, type: 'USER_INDEX' },
    { title: 'Profile Created Date (ignore time)', _id: 'PROFILE_CREATED_DATE', isNumber: false, type: 'USER_INDEX' },
    { title: 'Profile Created Date and time', _id: 'PROFILE_CREATED_DATE_TIME', isNumber: false, type: 'USER_INDEX' },
    { title: 'Relationship Type', _id: 'RELATIONSHIP_TYPE', isNumber: false, type: 'USER_INDEX' },
    { title: 'Relationship Names (Last Name, First Name)', _id: 'RELATIONSHIP_NAMES', isNumber: false, type: 'USER_INDEX' },
    { title: 'Form Submitted Name', _id: 'FORM_SUBMITTED_NAME', isNumber: false, type: 'USER_INDEX' },
    { title: 'Form Submitted Date (ignore time)', _id: 'FORM_SUBMITTED_DATE', isNumber: false, type: 'USER_INDEX' },
    { title: 'Form Submitted Date and time', _id: 'FORM_SUBMITTED_DATE_TIME', isNumber: false, type: 'USER_INDEX' },
];

// employee data points

export const timesheetsDataPoints = [
    { title: 'Employee Name (Last Name)', _id: 'EMPLOYEE_LAST_NAME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Employee Name (First Name)', _id: 'EMPLOYEE_FIRST_NAME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Employee Name (Last Name, First Name)', _id: 'EMPLOYEE_FULL_NAME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Employee (Nickname)', _id: 'EMPLOYEE_NICKNAME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Department', _id: 'DEPARTMENT', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Title', _id: 'TITLE', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Wage', _id: 'WAGE', isNumber: true, type: 'TIMESHEETS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Start Time (Date and Time)', _id: 'START_TIME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'End Time (Date and Time)', _id: 'END_TIME', isNumber: false, type: 'TIMESHEETS' },
    { title: 'Total Hours', _id: 'TOTAL_HOURS', isNumber: true, type: 'TIMESHEETS' },
    { title: 'Total Pay', _id: 'TOTAL_PAY', isNumber: true, type: 'TIMESHEETS' },
    { title: 'Clock In/Out Comment', _id: 'CLOCK_COMMENT', isNumber: false, type: 'TIMESHEETS' },
];

export const employeeEventsDataPoints = [
    { title: 'Employee Name (Last Name)', _id: 'EMPLOYEE_LAST_NAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Employee Name (First Name)', _id: 'EMPLOYEE_FIRST_NAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Employee Name (Last Name, First Name)', _id: 'EMPLOYEE_FULL_NAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Employee (Nickname)', _id: 'EMPLOYEE_NICKNAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Department', _id: 'DEPARTMENT', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Title', _id: 'TITLE', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Type', _id: 'EVENT_TYPE', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Name', _id: 'EVENT_NAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Date (ignore time)', _id: 'EVENT_DATE_ONLY', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Date and Time', _id: 'EVENT_DATE_TIME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Commission', _id: 'EVENT_COMMISSION', isNumber: true, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Level', _id: 'EVENT_LEVEL', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Event Location', _id: 'EVENT_LOCATION', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Service Name', _id: 'SERVICE_NAME', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Service Price', _id: 'SERVICE_PRICE', isNumber: true, type: 'EMPLOYEE_EVENTS' },
    { title: 'Attendance Quantity', _id: 'ATTENDANCE_QUANTITY', isNumber: true, type: 'EMPLOYEE_EVENTS' },
    { title: 'Attendance List (Last Name, First Name)', _id: 'ATTENDANCE_LIST', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Attendance Status', _id: 'ATTENDANCE_STATUS', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Completed Date', _id: 'COMPLETED_DATE', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Member Verification', _id: 'MEMBER_VERIFICATION', isNumber: false, type: 'EMPLOYEE_EVENTS' },
    { title: 'Employee Verification', _id: 'EMPLOYEE_VERIFICATION', isNumber: false, type: 'EMPLOYEE_EVENTS' },
];

export const commissionsDataPoints = [
    { title: 'Employee Name (Last Name)', _id: 'EMPLOYEE_LAST_NAME', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Employee Name (First Name)', _id: 'EMPLOYEE_FIRST_NAME', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Employee Name (Last Name, First Name)', _id: 'EMPLOYEE_FULL_NAME', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Employee (Nickname)', _id: 'EMPLOYEE_NICKNAME', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Department', _id: 'DEPARTMENT', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Title', _id: 'TITLE', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Commission Group', _id: 'COMMISSION_GROUP', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Sales Code', _id: 'SALES_CODE', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Sales Item', _id: 'SALES_ITEM', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Sales Quantity', _id: 'SALES_QUANTITY', isNumber: true, type: 'COMMISSIONS' },
    { title: 'Sales Price', _id: 'SALES_PRICE', isNumber: true, type: 'COMMISSIONS' },
    { title: 'Sales Commission', _id: 'SALES_COMMISSION', isNumber: true, type: 'COMMISSIONS' },
    { title: 'Sales Date (ignore time)', _id: 'SALES_DATE_ONLY', isNumber: false, type: 'COMMISSIONS' },
    { title: 'Sales Date and Time', _id: 'SALES_DATE_TIME', isNumber: false, type: 'COMMISSIONS' },
];

export const employeeTasksDataPoints = [
    { title: 'Employee Name (Last Name)', _id: 'EMPLOYEE_LAST_NAME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Employee Name (First Name)', _id: 'EMPLOYEE_FIRST_NAME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Employee Name (Last Name, First Name)', _id: 'EMPLOYEE_FULL_NAME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Employee (Nickname)', _id: 'EMPLOYEE_NICKNAME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Department', _id: 'DEPARTMENT', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Title', _id: 'TITLE', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Member Assigned (Last name, First Name)', _id: 'MEMBER_ASSIGNED_FULL_NAME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Member Primary #', _id: 'MEMBER_PRIMARY_NUMBER', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Member Cell #', _id: 'MEMBER_CELL_NUMBER', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Member Email', _id: 'MEMBER_EMAIL', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Agreement Number', _id: 'AGREEMENT_NUMBER', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Member Barcode', _id: 'MEMBER_BARCODE', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Task Type', _id: 'TASK_TYPE', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Task Status', _id: 'TASK_STATUS', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Last Status Update Date (ignore Time)', _id: 'LAST_STATUS_UPDATE_DATE', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Last Status Update Date and Time', _id: 'LAST_STATUS_UPDATE_DATE_TIME', isNumber: false, type: 'EMPLOYEE_TASKS' },
    { title: 'Task Notes', _id: 'TASK_NOTES', isNumber: false, type: 'EMPLOYEE_TASKS' },
];

export const employeeResourcesDataPoints = [
    { title: 'Resource Type', _id: 'RESOURCE_TYPE', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Resource Name', _id: 'RESOURCE_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Total Quantity', _id: 'TOTAL_QUANTITY', isNumber: true, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Quantity Available', _id: 'QUANTITY_AVAILABLE', isNumber: true, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Quantity Reserved', _id: 'QUANTITY_RESERVED', isNumber: true, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Quantity Past Due', _id: 'QUANTITY_PAST_DUE', isNumber: true, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Amount Past Due', _id: 'AMOUNT_PAST_DUE', isNumber: true, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Member Name (Last, First)', _id: 'MEMBER_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Event Name', _id: 'EVENT_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Employee Name (Last Name)', _id: 'EMPLOYEE_LAST_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Employee Name (First Name)', _id: 'EMPLOYEE_FIRST_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Employee Name (Last Name, First Name)', _id: 'EMPLOYEE_FULL_NAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Employee (Nickname)', _id: 'EMPLOYEE_NICKNAME', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
    { title: 'Club #', _id: 'CLUB_NUMBER', isNumber: false, type: 'EMPLOYEE_RESOURCES' },
];

export const inventoryDataPoints = [
    { title: 'Item Name', _id: 'ITEM_NAME', isNumber: false, type: 'INVENTORY' },
    { title: 'Item Quantity (On Hand)', _id: 'ITEM_QUANTITY_ON_HAND', isNumber: true, type: 'INVENTORY' },
    { title: 'Item Quantity (Available)', _id: 'ITEM_QUANTITY_AVAILABLE', isNumber: true, type: 'INVENTORY' },
    { title: 'Item Quantity (Outbound)', _id: 'ITEM_QUANTITY_OUTBOUND', isNumber: true, type: 'INVENTORY' },
    { title: 'Item Quantity (Inbound)', _id: 'ITEM_QUANTITY_INBOUND', isNumber: true, type: 'INVENTORY' },
    { title: 'Item Location', _id: 'ITEM_LOCATION', isNumber: false, type: 'INVENTORY' },
    { title: 'Item Sku', _id: 'ITEM_SKU', isNumber: false, type: 'INVENTORY' },
    { title: 'Item UPC', _id: 'ITEM_UPC', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Name', _id: 'VENDOR_NAME', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Location', _id: 'VENDOR_LOCATION', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Phone #', _id: 'VENDOR_PHONE', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Email', _id: 'VENDOR_EMAIL', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Website', _id: 'VENDOR_WEBSITE', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Primary Contact Method', _id: 'VENDOR_PRIMARY_CONTACT_METHOD', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Rep', _id: 'VENDOR_REP', isNumber: false, type: 'INVENTORY' },
    { title: 'Alternate Vendor', _id: 'ALTERNATE_VENDOR', isNumber: false, type: 'INVENTORY' },
    { title: 'Vendor Lead Time', _id: 'VENDOR_LEAD_TIME', isNumber: false, type: 'INVENTORY' },
    { title: 'Minimum Order Qty', _id: 'MIN_ORDER_QTY', isNumber: true, type: 'INVENTORY' },
    { title: 'Maximum Order Qty', _id: 'MAX_ORDER_QTY', isNumber: true, type: 'INVENTORY' },
    { title: 'Case Qty', _id: 'CASE_QTY', isNumber: true, type: 'INVENTORY' },
    { title: 'Item Weight', _id: 'ITEM_WEIGHT', isNumber: true, type: 'INVENTORY' },
    { title: 'Case Weight', _id: 'CASE_WEIGHT', isNumber: true, type: 'INVENTORY' },
    { title: 'Next Expiration Date', _id: 'NEXT_EXPIRATION_DATE', isNumber: false, type: 'INVENTORY' },
    { title: 'Oldest Expiration Date', _id: 'OLDEST_EXPIRATION_DATE', isNumber: false, type: 'INVENTORY' },
    { title: 'Last Order Date', _id: 'LAST_ORDER_DATE', isNumber: false, type: 'INVENTORY' },
    { title: 'Sales Since Last Order Date', _id: 'SALES_SINCE_LAST_ORDER', isNumber: true, type: 'INVENTORY' },
    { title: 'Delivery Received Employee (Last Name, First Name)', _id: 'DELIVERY_RECEIVED_EMPLOYEE', isNumber: false, type: 'INVENTORY' },
    { title: 'Delivery Status', _id: 'DELIVERY_STATUS', isNumber: false, type: 'INVENTORY' },
];

// ─── Lookup map: DATA_POINTS_MAP[userType][ruleType] → dataPoints array ──

const DATA_POINTS_MAP = {
    MEMBER: {
        PURCHASED_SERVICE: purchasedServiceDataPoints,
        PURCHASED_PRODUCT: purchasedProductDataPoints,
        AGREEMENT: agreementDataPoints,
        EVENT: eventDataPoints,
        REWARD: rewardsDataPoints,
        TASK: tasksDataPoints,
        RESOURCE: resourcesDataPoints,
        SERVICE: serviceDataPoints,
        USER_INDEX: userIndexDataPoints,
    },
    EMPLOYEE: {
        EVENT: employeeEventsDataPoints,
        TASK: employeeTasksDataPoints,
        RESOURCE: employeeResourcesDataPoints,
        TIMESHEET: timesheetsDataPoints,
        COMMISSION: commissionsDataPoints,
    },
};

/**
 * Returns the data points array for a given userType + ruleType combination.
 */
export const getDataPoints = (userType, ruleType) => {
    return DATA_POINTS_MAP[userType]?.[ruleType] || [];
};
