export const POS = {
  CATEGORIES: "/point-of-sale/categories",
  TOP_SELLING_CATALOG_ITEMS: "/point-of-sale/top-selling-catalog-items",
  CATALOG_ITEMS: "/point-of-sale/catalog-items",
  MEMBERS_LIST: "/point-of-sale/members-list",
  FILTERS: "/point-of-sale/filters",
  TAGS: "/point-of-sale/tags",
  SALE: "/point-of-sale/sale",
  REGISTER: "/point-of-sale/registers",
  REGISTER_START: "/point-of-sale/registers/start",
  REGISTER_END: "/point-of-sale/registers/end",
  REGISTER_STATUS: "/point-of-sale/registers/status",
  SAVED_CART: "/point-of-sale/saved-cart",
  VALIDATE_PROMO_CODE: "/point-of-sale/validate-promo-code",
  VALIDATE_SALES_CODE: "/point-of-sale/validate-sales-code",
  VALIDATE_DISCOUNT_USAGE: "/point-of-sale/validate-discount-usage",
  VALIDATE_REDEMPTION: "/point-of-sale/validate-redemption",
  BALANCE_HISTORY: "/point-of-sale/balance-history/",
  IPOS_CARDS: "/point-of-sale/ipos-cards/",
};
